// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fztqhefzxxjcsbusokvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ6dHFoZWZ6eHhqY3NidXNva3ZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNDg2ODgsImV4cCI6MjA1OTkyNDY4OH0.7HNEhP8Bi-16zhXWb-M6EZ_6kvpxgq5PL-CBqkvElfA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);